### ISSUE TITLE
The requested operation cannot be performed on a file with a user-mapped section open.

### ISSUE THREAD

**Issue by earhax** [TurboLabIt/StartTileBackup#3]
I backed up my tiles from one Windows 10 workstation, copied the backup folder to another workstation, and tried restoring the tiles from my other PC to the new one. It gets stuck in the middle of the restore with the error "The requested operation cannot be performed on a file with a user-mapped section open."

Here is a log from the command prompt when I ran the restore.bat as admin:

`StartTileBackup
----------------
A simple batch script to backup and restore the Start menu tiles and pinned apps.

Official project page: https://github.com/TurboLabIt/StartTileBackup

PRESS A KEY TO **RESTORE**!
Press any key to continue . . .
### Killing File Explorer...
SUCCESS: The process "explorer.exe" with PID 25628 has been terminated.
### File restore in progress!

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Wednesday, May 15, 2019 12:19:52
   Source : C:\Users\mmaksim\Downloads\StartTileBackup-master\backup\CloudStore\
     Dest : C:\Users\mmaksim\AppData\Local\Microsoft\Windows\CloudStore\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

          New Dir          0    C:\Users\mmaksim\Downloads\StartTileBackup-master\backup\CloudStore\

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         1         1         0         0         0         0
   Files :         0         0         0         0         0         0
   Bytes :         0         0         0         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00
   Ended : Wednesday, May 15, 2019 12:19:52

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Wednesday, May 15, 2019 12:19:52
   Source : C:\Users\mmaksim\Downloads\StartTileBackup-master\backup\Caches\
     Dest : C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Caches\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

          New Dir          7    C:\Users\mmaksim\Downloads\StartTileBackup-master\backup\Caches\
100%        New File               16384        cversions.1.db
100%        New File               16384        cversions.3.db
100%        New File              414768        {35259259-B905-4D30-88C9-B63C603DA134}.3.ver0x0000000000000002.db
100%        New File              451504        {3DA71D5A-20CC-432F-A115-DFE92379E91F}.3.ver0x0000000000000246.db
100%        New File              461168        {3DA71D5A-20CC-432F-A115-DFE92379E91F}.3.ver0x0000000000000247.db
100%        New File               1.1 m        {AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x0000000000000039.db
100%        New File              597672        {AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x000000000000003a.db

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         1         1         0         0         0         0
   Files :         7         7         0         0         0         0
   Bytes :    3.03 m    3.03 m         0         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00

   Speed :           289261818 Bytes/sec.
   Speed :           16551.694 MegaBytes/min.
   Ended : Wednesday, May 15, 2019 12:19:52

C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\ICONCA~1\icnE4C2.tmp - Access is denied.
C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\ICONCA~1\icnE4C4.tmp - Access is denied.
C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\ICONCA~1\icnE4C5.tmp - Access is denied.
C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\iconcache_idx.db - Access is denied.
C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\thumbcache_16.db - Access is denied.
C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\thumbcache_32.db - Access is denied.
C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\thumbcache_idx.db - Access is denied.

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Wednesday, May 15, 2019 12:19:52
   Source : C:\Users\mmaksim\Downloads\StartTileBackup-master\backup\Explorer\
     Dest : C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                          32    C:\Users\mmaksim\Downloads\StartTileBackup-master\backup\Explorer\
        *EXTRA Dir        -1    C:\Users\mmaksim\AppData\Local\Microsoft\Windows\Explorer\IconCacheToDelete\
100%        New File              729088        ExplorerStartupLog.etl
100%        New File               32768        ExplorerStartupLog_RunOnce.etl
100%        New File                  24        iconcache_1280.db
100%        New File              53.0 m        iconcache_16.db
100%        New File                  24        iconcache_1920.db
100%        New File              57.0 m        iconcache_256.db
100%        New File                  24        iconcache_2560.db
100%        New File             109.0 m        iconcache_32.db
100%        New File              28.0 m        iconcache_48.db
100%        New File                  24        iconcache_768.db
100%        New File                  24        iconcache_96.db
100%        New File                  24        iconcache_custom_stream.db
100%        New File                  24        iconcache_exif.db
            Older                  7.1 m        iconcache_idx.db
2019/05/15 12:19:52 ERROR 1224 (0x000004C8) Copying File C:\Users\mmaksim\Downloads\StartTileBackup-master\backup\Explorer\iconcache_idx.db
The requested operation cannot be performed on a file with a user-mapped section open.
Waiting 30 seconds...`

I hope there is some simple solution to this issue as it would save a lot of time being able to restore the tiles from one machine to another.

**Comment by dwrolvink** [comment]
Hi, I just tried to do a backup and a restore.
Since I have limited resources, I did both on the same machine, removing a tile to test if it worked.

I'll describe my steps, maybe you did something else, so you can try my steps.
Seeing as it's an access denied message, you might additionally try to restart the machine first, **and not open any programs prior to restoring.**

Another issue might be that you don't have full rights to the locations you're writing to. Make sure you are local administrator, and that there aren't any group policies limiting your rights.

1. Download a fresh .zip from this project and unzip
2. Open cmd as administrator
3. `cd C:\Users\dorus\Downloads\StartTileBackup-master\StartTileBackup-master`
4. `backup.bat [enter]`
5. Remove tile from start menu for testing purposes
6. Repeat step 2&3
7. `restore.bat`

Let us know if that works locally at least. (backup and restore in the same session)

**Comment by earhax** [comment]
I checked the rights and everything else. I used process explorer to see
what else might have been locking the files and killed all other apps,
which resolved the issue. However, the tiles I backed up on my other PC are
still not restored to this PC, even though I have mirrored my windows user
folder to it, including appdata/roaming.

One other issue: it would be great if the process would restore any open
explorer windows when relaunching explorer. Right now when the process is
killed and restarted, any explorer windows I had open are gone.

If you can find a way to make this work between PCs, it would be far more
useful. Please let me know.

Another way you might try testing it is by using a different user
account/login on the same PC (if you don't have a second PC to test it on).
Let me know if that works for you.

I'm wondering if there may be some incompatibility due to machine IDs or
something of that nature which prevents restoring tiles from one machine to
another.

**Comment by dwrolvink** [comment]
Just to be clear, I'm not the author of this script. I used it for work to set a startmenu on newly installed machines. I forked and extended it to also take the taskbar with in the backup/restore. his worked really well 1.5 years ago, haven't used it since. I got an email with your question because I have a fork of it. T

I just did the following:
- Copied the folder over (that I had from my previous post) to a new machine.
- Both users have the same name, profiles are different though
- Source is a VM, target a laptop
- Source and target destinations were both ~/Downloads
- Ran restore.bat on the target machine

Worked flawlessly for me. 
Do the applications for which you have start tiles backupped exist on the target machine?
Are both machines windows 10 machines? Same version also?

It's a shame that it closes all your explorer windows. You're free to extend the script so it doesn't do that. Normally though, you'd use this once. If you're gonna use it to sync two machines, you might have it run at startup or something similar.

**Comment by JEmlay** [comment]
Weird, never had a problem using this now all of a sudden I can't get it to work at all.  Multiple new VMs all with the same problem.

"The requested operation cannot be performed on a file with a user-mapped section open."

Makes no sense.  These files are locked by some unknown process.  Nothing is claiming them.
