### ISSUE TITLE
Corrupted my start menu and I became unable to pin anything on it

### ISSUE THREAD

**Issue by Thespikedballofdoom** [TurboLabIt/StartTileBackup#5]
I know this is an old script, but I only narrowly eked out because system restore saved my ass and I had installed a program earlier which set one.

**Comment by ZaneCEO** [comment]
Hi! Thank you for taking the time to report the issue. This script is indeed quite old, and I've not maintained it in a long time. I'm going to add a "do not use!" note in the readme and mark the repo as deprecated later today.
